Fix/repository refactor
LesGolems/RateMyEPFL pull request #297
Opened 2022-05-26 14:44 UTC by AlexandreMessmer

Refactor the asynchronous operations of the repositories using kotlin coroutines. Since it was required to implement the loading of the PostList, it also implements it.

2022-05-30 21:11 UTC, NicolasMatekalo approved these changes

2022-05-30 21:12 UTC, mbouilloud approved these changes

2022-05-30 22:42 UTC, jmettler27 approved these changes

2022-05-30 22:46 UTC, jmettler27 commented on app/src/main/res/layout/fragment_comment_list.xml
> +            android:id="@+id/commentRecyclerView"
I think the code would be simpler if we don't use an id and reuse `post_list_layout `for all list fragments, without passing an id as an argument

2022-05-30 23:30 UTC, mbouilloud requested changes
Bug on like/dislike, check that before merging anything.

2022-05-31 00:15 UTC, mbouilloud approved these changes
I am fixing the likes in a next branch.

2022-05-31 00:15 UTC, merged